linters:
  disable-all: true
  enable:
    - revive # Modern replacement for golint
    - gofmt # Formatting
    - govet # Suspicious constructs
    - errcheck # Error handling
    - staticcheck # Static analysis
    - gosimple # Code simplification
    - ineffassign # Ineffective assignments
    - typecheck # Type checks
    - unused # Unused code

run:
  timeout: 5m

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
